version: "3"
services:
  web:
    image: llamabagel/transpo-server:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - /etc/transpo/config:/app/config
      - /var/transpo/packages:/app/packages
networks:
  webnet: